# Generated by Django 2.2 on 2021-04-17 20:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PickupApp', '0002_auto_20210407_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='Court',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=45)),
                ('Location', models.CharField(max_length=45)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Userincourt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User_in_court', to='PickupApp.User')),
            ],
        ),
    ]
