# Generated by Django 2.2 on 2021-04-17 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PickupApp', '0003_court'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='court',
            name='Userincourt',
        ),
        migrations.AddField(
            model_name='court',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='court_withuser', to='PickupApp.User'),
        ),
    ]
