# Generated by Django 2.2 on 2021-04-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PickupApp', '0004_auto_20210417_1722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='court',
            old_name='Location',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='court',
            old_name='Name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Age',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='First_Name',
            new_name='first_Name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Hometown',
            new_name='hometown',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Last_Name',
            new_name='last_Name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='Username',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='court',
            name='User',
        ),
        migrations.AddField(
            model_name='user',
            name='courts',
            field=models.ManyToManyField(null=True, related_name='players', to='PickupApp.Court'),
        ),
    ]
