# Generated by Django 2.2 on 2021-04-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PickupApp', '0005_auto_20210418_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='courts',
            field=models.ManyToManyField(related_name='players', to='PickupApp.Court'),
        ),
    ]
