# Generated by Django 2.2 on 2021-04-19 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PickupApp', '0007_court_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='court',
            name='link',
            field=models.TextField(null=True),
        ),
    ]
