# Generated by Django 2.2 on 2021-05-11 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PickupApp', '0009_feed'),
    ]

    operations = [
        migrations.CreateModel(
            name='comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('CLiker', models.ManyToManyField(related_name='comment_liked', to='PickupApp.User')),
                ('Commenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Posted_comment', to='PickupApp.User')),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('Liker', models.ManyToManyField(related_name='Feed_liked', to='PickupApp.User')),
                ('Poster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Quotes_posted', to='PickupApp.User')),
            ],
        ),
        migrations.DeleteModel(
            name='Feed',
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Commented_Post', to='PickupApp.Post'),
        ),
    ]
