# Generated by Django 2.2 on 2021-05-11 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PickupApp', '0010_auto_20210510_2354'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='description',
            new_name='Comment_field',
        ),
    ]
