# Generated by Django 2.2 on 2021-05-12 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PickupApp', '0011_auto_20210511_1253'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='CLiker',
            new_name='cLiker',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Comment_field',
            new_name='comment_field',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Commenter',
            new_name='commenter',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Liker',
            new_name='liker',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Poster',
            new_name='poster',
        ),
    ]
