# Generated by Django 2.2 on 2021-05-12 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PickupApp', '0012_auto_20210512_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='commenter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posted_comment', to='PickupApp.User'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_post', to='PickupApp.Post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='liker',
            field=models.ManyToManyField(related_name='feed_liked', to='PickupApp.User'),
        ),
        migrations.AlterField(
            model_name='post',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quotes_posted', to='PickupApp.User'),
        ),
    ]
