# Generated by Django 2.2 on 2021-05-12 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PickupApp', '0013_auto_20210512_1426'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='cLiker',
            new_name='cliker',
        ),
    ]
